import { Cormorant, Lato } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navigation/Navbar";
import MobileNav from "@/components/mobileNavigation/MobileNav";
import Footer from "@/components/navigation/Footer";
import FooterBottomBanner from "@/components/navigation/FooterBottomBanner";
import MobileFooter from "@/components/mobileNavigation/MobileFooter";
import LenisProvider from "@/components/desktopSections/scroll/lenis/LenisProvider";

const cormorant = Cormorant({
  weight: ["400", "600"],
  subsets: ["latin"],
  variable: "--font-cormorant",
});

const lato = Lato({
  weight: ["100", "300", "400", "700", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--font-lato",
});

export const metadata = {
  title: "Indiefluence Garage",
  description: "Generated by create next app",
};

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  viewportFit: 'cover',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${cormorant.variable} ${lato.variable} antialiased`}>
        {/* ================= MOBILE ================= */}
        <div className="block md:hidden min-h-screen flex flex-col">
          <MobileNav />
          <main className="flex-1">{children}</main>
          <MobileFooter />
          <FooterBottomBanner/>
        </div>

        {/* ================= TABLET BLOCK SCREEN ================= */}
        <div className="hidden md:flex lg:hidden h-screen w-full items-center justify-center bg-[#FFFDF1] px-6 text-center">
          <div className="max-w-md space-y-6">
            <h2 className="text-3xl font-semibold">
              Tablet View Not Supported
            </h2>
            <p className="text-base text-gray-700">
              This experience is crafted specifically for mobile and desktop
              screens. Please switch to a mobile device or view this site on a
              desktop for the best experience.
            </p>
            <div className="flex justify-center gap-4 text-sm text-gray-500">
              <span>📱 Mobile</span>
              <span>🖥 Desktop</span>
            </div>
          </div>
        </div>

        {/* ================= DESKTOP ================= */}
        <div className="hidden lg:block">
          <Navbar />
          <div className="h-20 w-full" aria-hidden="true" />
          <LenisProvider>
            <main>{children}</main>
          </LenisProvider>
          <Footer />
          <FooterBottomBanner />
        </div>
      </body>
    </html>
  );
}